#!/sbin/busybox sh
#
# scrip

BB=/sbin/busybox;

$BB mount -o remount,rw,nosuid,nodev /cache;
$BB mount -o remount,rw,nosuid,nodev /data;
$BB mount -o remount,rw /;
$BB mount -o remount,rw /lib/modules;

# cleaning
$BB rm -rf /cache/lost+found/* >/dev/null 2>&1
$BB rm -rf /data/lost+found/* >/dev/null 2>&1
$BB rm -rf /data/tombstones/* >/dev/null 2>&1
$BB rm -rf /data/anr/* >/dev/null 2>&1

# critical Permissions fix
$BB chown -R root:system /sys/devices/system/cpu/ >/dev/null 2>&1
$BB chown -R system:system /data/anr >/dev/null 2>&1
$BB chown -R root:radio /data/property/ >/dev/null 2>&1
$BB chmod -R 777 /tmp/ >/dev/null 2>&1
$BB chmod -R 6755 /sbin/ext >/dev/null 2>&1
$BB chmod -R 755 /sbin/ext/* >/dev/null 2>&1
$BB chmod -R 0777 /dev/cpuctl/ >/dev/null 2>&1
$BB chmod -R 0777 /data/system/inputmethod/ >/dev/null 2>&1
$BB chmod -R 0777 /sys/devices/system/cpu/ >/dev/null 2>&1
$BB chmod -R 0777 /data/anr/ >/dev/null 2>&1
$BB chmod 0744 /proc/cmdline >/dev/null 2>&1
$BB chmod -R 0770 /data/property/ >/dev/null 2>&1
$BB chmod -R 0400 /data/tombstones >/dev/null 2>&1

# fix owners on critical folders
$BB chown -R root:root /tmp >/dev/null 2>&1
$BB chown -R root:root /res >/dev/null 2>&1
$BB chown -R root:root /sbin >/dev/null 2>&1
$BB chown -R root:root /lib >/dev/null 2>&1

$BB sync >/dev/null 2>&1